### ISSUE TITLE
row/column matrices between projectives in QPA

### ISSUE THREAD

**Issue by mahrud** [gap-packages/qpa#99]
Unless I'm very confused, QPA seems to be displaying matrices of incorrect size in some cases.

Say I have a projective resolution with two nonzero terms:
```
--- -> 5: P3 + P3 + P3 -> 4: P2 -> 0
```
The matrices (from right to left) should be 1x3 then 3x0 then 0x0 forever, but instead I get 1x3 then 1x3 (!) then 1x1 forever!
```
[ [ (1)*x2, (1)*y2, (1)*z2 ] ]
[ [ <zero> of ..., <zero> of ..., <zero> of ... ] ]
[ [ <zero> of ... ] ]
[ [ <zero> of ... ] ]
[ [ <zero> of ... ] ]
```
Also, what are the `<zero> of ...` doing there? Am I doing something wrong?

Here is my whole script:
```
LoadPackage("qpa");

Q := Quiver( 3, [[1, 2, "x1"], [1, 2, "y1"], [1, 2, "z1"], [2, 3, "x2"], [2, 3, "y2"], [2, 3, "z2"]] );
kQ := PathAlgebra(Rationals, Q);
AssignGeneratorVariables(kQ);
relations := [x1*y2 - x2*y1, x1*z2 - x2*z1, y1*z2 - y2*z1];
A := kQ/relations;

S := SimpleModules(A);
C := CatOfRightAlgebraModules(A);

M := StalkComplex(C, S[2], 0);
P := ProjectiveResolutionOfComplex(M);
for i in [1..2] do
    diff := DifferentialOfComplex(P, i);
    mat := MatrixOfHomomorphismBetweenProjectives(diff);
    Print(mat, "\n");
od;
P;
```

**Comment by sunnyquiver** [comment]
Indeed there is a bug in MatrixOfHomomorphismBetweenProjectives. It is hopefully fixed in the latest commit 41fca7a. The zero map between two indecompables projectives are chosen to be representated by the zero 1x1-matrix. One of course could represent it differently, but this is the choice that have been done. In addition, historically GAP has not had any structure for matrices with zero columns or zero rows. The zero element in a (quotient of a) path algebra is presented by "<zero> of ...".

**Comment by mahrud** [comment]
Thanks!

> The zero map between two indecompables projectives are chosen to be representated by the zero 1x1-matrix. One of course could represent it differently, but this is the choice that have been done. In addition, historically GAP has not had any structure for matrices with zero columns or zero rows.

For what it's worth, in Macaulay2 `entries(M)` prints `{{}, {}, {}}` for a 3x0 map (three rows, zero columns) and `{}` for any 0xn map (because there are no rows, so number of columns can't be determined).

> The zero element in a (quotient of a) path algebra is presented by " of ...".

Is there a way to get it to print as just "0", at least just for me?  Perhaps by fiddling with `PrintObj` or `ViewObj` methods?

**Comment by mahrud** [comment]
Something is still wrong. Here's an example:
```
LoadPackage("qpa");

Q := Quiver( 4, [[1, 2, "z_0"], [1, 2, "x_0"], [1, 3, "w_0"], [2, 3, "y_0"], [2, 4, "w_1"], [3, 4, "z_1"], [3, 4, "x_1"]] );
kQ := PathAlgebra(Rationals, Q);
AssignGeneratorVariables(kQ);
relations := [z_0*w_1 - w_0*z_1, x_0*w_1 - w_0*x_1];
A := kQ/relations;

S := SimpleModules(A);
C := CatOfRightAlgebraModules(A);

SM := S[2];
M := StalkComplex(C, SM, 0);
P := ProjectiveResolutionOfComplex(M);

diff := DifferentialOfComplex(P, 1);
mat := MatrixOfHomomorphismBetweenProjectives(diff);

diff := DifferentialOfComplex(P, 2);
mat := MatrixOfHomomorphismBetweenProjectives(diff);
```
This would imply the complex
```
--- -> 5: P3 + P4 -> 4: P2 -> 0
```
has differentials:
```
[ [ (1)*y_0, (1)*w_1 ] ]
[ [ <zero> of ... ], [ <zero> of ... ] ]
```
Specifically, the second map should be 2x0 but is 2x1 here.
Why not just print this as `[ [ ], [ ] ]`?

I imagine this is also related to why QPA fails to find length of this complex:
```
gap> LengthOfComplex(P);
fail
```

**Comment by sunnyquiver** [comment]
Concerning the output, as I said before "The zero map between two indecompables projectives are chosen to be representated by the zero 1x1-matrix. One of course could represent it differently, but this is the choice that have been done." 

Concerning the return of `fail` from the `LengthOfComplex` call, I guess that this can be a more involved question. I have not written the code for the complexes-part, so I am not totally familiar with the inner workings of it. Hence, I have to ask the people who wrote it, if they remember anything that can help. Because, as in this example, you have a complex which is a projective resolution of a module. In principle the projective dimension of this module can be infinite or very large, how would you compute the length of the complex? Even if you knew that the module had finite projective dimension, it is unknown how big it can be. So sometimes one has to accept answering just `fail`, but I am not sure if this is such a situation.

**Comment by mahrud** [comment]
> The zero map between two indecompables projectives are chosen to be representated by the zero 1x1-matrix. 

Could you point me to where in the code I would have to look if I wanted to change this locally?

> In principle the projective dimension of this module can be infinite or very large, how would you compute the length of the complex? Even if you knew that the module had finite projective dimension, it is unknown how big it can be. So sometimes one has to accept answering just fail, but I am not sure if this is such a situation.

Once a differential is computed to be zero, the projective resolution is finished and the projective dimension is known, no?

**Comment by sunnyquiver** [comment]
How the output of MatrixOfHomomorphismBetwenProjectives are given are handle by how GAP is printing matrices, as far as I can understand. Hence, you need to go into the GAP code and fiddle with the appropriate commands. I am not sure how to do this. Sorry. 

Yes, there could be a check when things are computed to set the length of the complex. But if you are going to write a function that computes the length of the complex, you would encounter the problems I mentioned. I don't see immediately how to do the first change, but I will consult the writers of the code and see what can be done.

Thank you very much for using QPA.
